FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# hela

Hela is a personal money management application.

## Expenses Collection [/expenses]

### List All Expenses [GET]

+ Response 200 (application/json)

        [
            {
                "description": "Grocery Shopping",
                "amount": 6250
            },
            {
                "description": "Fuel Refill",
                "amount": 1000
            }
        ]

### Create a Expense [POST]

You may create your own expense record using this action. It takes a JSON
object containing a description and an amount.

+ Request (application/json)

            {
                "description": "Grocery Shopping",
                "amount": 6250
            }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "description": "Grocery Shopping",
                "amount": 6250,
                "created_at":'',
                "updated_at":''
            }

## Expense Categories Collection [/expense_categories]

### List All Expense Categories [GET]

+ Response 200 (application/json)

        [
            {
                "name": "Food"
            },
            {
                "name": "Transport"
            }
        ]

### Create a Expense Category [POST]

You may create your own expense category using this action. It takes a JSON
object containing a name.

+ Request (application/json)

        {
            "name": "Shopping"
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/2

    + Body

            {
                "name": "Transport",
                "created_at": "2015-08-05T08:40:51.620Z",
                "updated_at": "2015-08-05T08:40:51.620Z"
            }
